STEP1: Create DEV Database & Schemas
**************************************
CREATE DATABASE IF NOT EXISTS DEV_DB;

CREATE SCHEMA IF NOT EXISTS DEV_DB.RAW;
CREATE SCHEMA IF NOT EXISTS DEV_DB.STAGE;
CREATE SCHEMA IF NOT EXISTS DEV_DB.CURATED;

STEP2: Create RAW Table (Append Only + Metadata)
**************************************
CREATE OR REPLACE TABLE DEV_DB.RAW.EMP_DATA_RAW (
    EMP_ID           VARCHAR,
    NAME             VARCHAR,
    TAX              NUMBER(10,2),
    SALARY           NUMBER(12,2),
    DOB              TIMESTAMP_NTZ,
    COUNTRY          VARCHAR,
    
    -- Metadata Columns
    FILE_NAME        VARCHAR,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PIPE_NAME        VARCHAR
);

STEP3: Create Storage Integration (DEV)
***************************************
CREATE OR REPLACE STORAGE INTEGRATION DEV_S3_EMP_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::265230572780:role/role-aws-s3-bkt-ex' 
STORAGE_ALLOWED_LOCATIONS = ('s3://aws-s3-bkt-ex/SnowflakeData/');  -- s3://aws-s3-bkt-ex/SnowflakeData/movies.csv


After creation:
DESC INTEGRATION DEV_S3_EMP_INT;
--STORAGE_AWS_IAM_USER_ARNp
--STORAGE_AWS_EXTERNAL_ID

Update IAM trust policy using EXTERNAL_ID.

STEP4: Create File Format (Strict but DEV-Friendly)
**************************************
CREATE OR REPLACE FILE FORMAT DEV_DB.STAGE.CSV_EMP_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
TRIM_SPACE = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

STEP5: Create External Stage (DEV)
**********************************
CREATE OR REPLACE STAGE DEV_DB.STAGE.EMP_EXT_STAGE
URL = 's3://aws-s3-bkt-ex/SnowflakeData/'
STORAGE_INTEGRATION = DEV_S3_EMP_INT
FILE_FORMAT = DEV_DB.STAGE.CSV_EMP_FORMAT;


Validate:
LIST @DEV_DB.STAGE.EMP_EXT_STAGE;
remove @DEV_DB.STAGE.EMP_EXT_STAGE/movies.csv

STEP6: Create DEV Snowpipe
**************************
CREATE OR REPLACE PIPE DEV_DB.STAGE.EMP_SNOWPIPE
AUTO_INGEST = TRUE
AS
COPY INTO DEV_DB.RAW.EMP_DATA_RAW
(EMP_ID,NAME,TAX,SALARY,DOB,COUNTRY,FILE_NAME,LOAD_TIMESTAMP,PIPE_NAME)
FROM
(SELECT $1, $2, $3, $4, $5, $6, METADATA$FILENAME, CURRENT_TIMESTAMP(), 'EMP_SNOWPIPE'
    FROM @DEV_DB.STAGE.EMP_EXT_STAGE
)
ON_ERROR = 'SKIP_FILE';

STEP7: Create Stream (DEV)
**************************
CREATE OR REPLACE STREAM DEV_DB.STAGE.EMP_STREAM
ON TABLE DEV_DB.RAW.EMP_DATA_RAW
APPEND_ONLY = TRUE;

STEP8: Create Curated Table (DEV)
**********************************
CREATE OR REPLACE TABLE DEV_DB.CURATED.EMP_DATA (
    EMP_ID     VARCHAR PRIMARY KEY,
    NAME       VARCHAR,
    TAX        NUMBER(10,2),
    SALARY     NUMBER(12,2),
    DOB        TIMESTAMP_NTZ,
    COUNTRY    VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ
);

STEP9: Create Merge Task (DEV — Faster Schedule)
********************************************
In DEV we use 1 minute for quick testing.

CREATE OR REPLACE TASK DEV_DB.STAGE.EMP_MERGE_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('DEV_DB.STAGE.EMP_STREAM')
AS
MERGE INTO DEV_DB.CURATED.EMP_DATA T
USING DEV_DB.STAGE.EMP_STREAM S
ON T.EMP_ID = S.EMP_ID

WHEN MATCHED THEN
UPDATE SET
    NAME = S.NAME,
    TAX = S.TAX,
    SALARY = S.SALARY,
    DOB = S.DOB,
    COUNTRY = S.COUNTRY,
    UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT
(
    EMP_ID, NAME, TAX, SALARY, DOB, COUNTRY, UPDATED_AT
)
VALUES
(
    S.EMP_ID, S.NAME, S.TAX, S.SALARY, S.DOB, S.COUNTRY, CURRENT_TIMESTAMP()
);

Enable task:
ALTER TASK DEV_DB.STAGE.EMP_MERGE_TASK RESUME;
==========================================================
🔎 DEV Monitoring Commands
Check Pipe Status
SELECT SYSTEM$PIPE_STATUS('DEV_DB.STAGE.EMP_SNOWPIPE');

Check Load History
SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'EMP_DATA_RAW',
        START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
    )
);

Check Stream Data
SELECT * FROM DEV_DB.STAGE.EMP_STREAM;
SELECT * FROM DEV_DB.RAW.EMP_DATA_RAW;
SELECT * FROM DEV_DB.CURATED.EMP_DATA;


DESC PIPE DEV_DB.STAGE.EMP_SNOWPIPE;
SELECT SYSTEM$PIPE_STATUS('DEV_DB.STAGE.EMP_SNOWPIPE');

ALTER PIPE DEV_DB.STAGE.EMP_SNOWPIPE REFRESH;

SELECT *
FROM TABLE(
    VALIDATE_PIPE_LOAD(
        PIPE_NAME => 'DEV_DB.STAGE.EMP_SNOWPIPE',
        START_TIME => DATEADD(HOUR,-2,CURRENT_TIMESTAMP())
    )
);

SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME=>'DEV_DB.RAW.EMP_DATA_RAW',
        START_TIME=>DATEADD(HOUR,-2,CURRENT_TIMESTAMP())
    )
);


